apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ravi-demo
namePrefix: dev-
resources:
  - ../../base
# images:
#   - name: varisacr.azurecr.io/bq-bc/bq-print-service
#     digest: sha256:50d83d86c791eb9792bb500740306153c515d1d7b65aefb0efd08d85c96ef7ce
configMapGenerator:
  - name: bq-print-service-properties-cm
    files:
      - .env.config.properties